export const SET_RESULTS = "SET_RESULTS";
export const SEARCH_POEM_DB_BY_TITLE = "SEARCH_POEM_DB_BY_TITLE";
export const SEARCH_POEM_DB_BY_AUTHOR = "SEARCH_POEM_DB_BY_AUTHOR";
export const SEARCH_POEM_DB_BY_LINE = "SEARCH_POEM_DB_BY_LINE";
export const SET_SEARCH_POEM_DB_RESULTS = "SET_SEARCH_POEM_DB_RESULTS";
